-- MIST Dallas 2026 National Qualifiers — with MIST IDs
-- Run in Supabase SQL Editor

-- Step 1: add mist_ids column if it doesn't exist
ALTER TABLE qualifiers ADD COLUMN IF NOT EXISTS mist_ids text;

-- Step 2: insert 2026 qualifier data
INSERT INTO qualifiers (year, name, school, category, placement, qualified_for_nationals, mist_ids) VALUES
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Knowledge Test 1', '1st', true, '0CRLU-V3AIS'),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Knowledge Test 1', '2nd', true, 'Z4SL7-UO78X'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Knowledge Test 1', '3rd', true, 'W72ZG-ULGE4'),
  (2026, 'Tulsa Peace Academy', 'Tulsa Peace Academy', 'Knowledge Test 1', '4th', true, '7TLAS-2TCBU'),
  (2026, 'Uplift North Hills Preparatory', 'Uplift North Hills Preparatory', 'Knowledge Test 1', '5th', true, '5OY1R-6J0LC'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Knowledge Test 2', '1st', true, 'W72ZG-SBU5E'),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Knowledge Test 2', '2nd', true, '0CRLU-4S9LS'),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Knowledge Test 2', '3rd', true, '0CRLU-1S9EU'),
  (2026, 'Wylie High School', 'Wylie High School', 'Knowledge Test 2', '4th', true, 'SETQW-VWL7G'),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Knowledge Test 2', '5th', true, 'Z4SL7-OIL75'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Knowledge Test 3', '1st', true, 'W72ZG-DHB1I'),
  (2026, 'Plano East Senior High School', 'Plano East Senior High School', 'Knowledge Test 3', '2nd', true, '007N4-KAR33'),
  (2026, 'Tulsa Peace Academy', 'Tulsa Peace Academy', 'Knowledge Test 3', '3rd', true, '7TLAS-1GTJU'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Knowledge Test 3', '4th', true, 'W72ZG-SWXNM'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Knowledge Test 3', '5th', true, 'W72ZG-VXH14'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Knowledge Test 4', '1st', true, 'W72ZG-2VO52'),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Knowledge Test 4', '2nd', true, '0CRLU-OVS24'),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Knowledge Test 4', '3rd', true, '0CRLU-EV12C'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Knowledge Test 4', '4th', true, 'W72ZG-EE6LG'),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Knowledge Test 4', '5th', true, 'BN4Y5-82JR8'),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Quran Memorization — Lvl 1 (Male)', '1st', true, '0CRLU-2UMNB'),
  (2026, 'Good Tree Academy', 'Good Tree Academy', 'Quran Memorization — Lvl 1 (Male)', '2nd', true, 'JNVET-YVJF9'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Quran Memorization — Lvl 1 (Male)', '3rd', true, 'W72ZG-AK7BQ'),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Quran Memorization — Lvl 1 (Male)', '4th', true, 'Z4SL7-WBB23'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Quran Memorization — Lvl 1 (Male)', '5th', true, 'W72ZG-QGBMZ'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Quran Memorization — Lvl 1 (Female)', '1st', true, 'W72ZG-9LZEA'),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Quran Memorization — Lvl 1 (Female)', '2nd', true, 'BN4Y5-1GTVH'),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Quran Memorization — Lvl 1 (Female)', '3rd', true, 'BN4Y5-KI53Z'),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Quran Memorization — Lvl 1 (Female)', '4th', true, 'Z4SL7-4KPUN'),
  (2026, 'The Muraqaba School', 'The Muraqaba School', 'Quran Memorization — Lvl 1 (Female)', '5th', true, 'QW9SP-LG8FW'),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Quran Memorization — Lvl 2 (Male)', '1st', true, 'Z4SL7-6RTW2'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Quran Memorization — Lvl 2 (Male)', '2nd', true, 'W72ZG-VFLS6'),
  (2026, 'Ikhlas Learning Foundation', 'Ikhlas Learning Foundation', 'Quran Memorization — Lvl 2 (Male)', '3rd', true, 'BIAVO-7HHBS'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Quran Memorization — Lvl 2 (Male)', '4th', true, 'W72ZG-7JVHN'),
  (2026, 'Plano East Senior High School', 'Plano East Senior High School', 'Quran Memorization — Lvl 2 (Male)', '5th', true, '007N4-HJISM'),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Quran Memorization — Lvl 2 (Female)', '1st', true, 'BN4Y5-WDRF4'),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Quran Memorization — Lvl 2 (Female)', '2nd', true, 'BN4Y5-I932C'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Quran Memorization — Lvl 2 (Female)', '3rd', true, 'W72ZG-AR62C'),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Quran Memorization — Lvl 2 (Female)', '4th', true, '0CRLU-UL6FQ'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Quran Memorization — Lvl 2 (Female)', '5th', true, 'W72ZG-H39KI'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Quran Memorization — Lvl 3 (Male)', '1st', true, 'W72ZG-UFCHL'),
  (2026, 'Epic Darul Quran Hifz School', 'Epic Darul Quran Hifz School', 'Quran Memorization — Lvl 3 (Male)', '2nd', true, 'EKR7Y-8PEIC'),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Quran Memorization — Lvl 3 (Male)', '3rd', true, 'Z4SL7-KFLFG'),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Quran Memorization — Lvl 3 (Male)', '4th', true, '0CRLU-04QG2'),
  (2026, 'Plano East Senior High School', 'Plano East Senior High School', 'Quran Memorization — Lvl 3 (Male)', '5th', true, '007N4-W85XK'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Quran Memorization — Lvl 3 (Female)', '1st', true, 'W72ZG-JH3T6'),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Quran Memorization — Lvl 3 (Female)', '2nd', true, 'BN4Y5-Y09YI'),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Quran Memorization — Lvl 3 (Female)', '3rd', true, 'BN4Y5-29JIR'),
  (2026, 'Good Tree Academy', 'Good Tree Academy', 'Quran Memorization — Lvl 3 (Female)', '4th', true, 'JNVET-ILK80'),
  (2026, 'Ikhlas Learning Foundation', 'Ikhlas Learning Foundation', 'Quran Memorization — Lvl 3 (Female)', '5th', true, 'BIAVO-X962R'),
  (2026, 'Epic Darul Quran Hifz School', 'Epic Darul Quran Hifz School', 'Quran Recitation (Male)', '1st', true, 'EKR7Y-ZJ7EP'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Quran Recitation (Male)', '2nd', true, 'W72ZG-Z6LG0'),
  (2026, 'IANT Quranic Academy', 'IANT Quranic Academy', 'Quran Recitation (Male)', '3rd', true, 'T0FA9-918AD'),
  (2026, 'IANT Quranic Academy', 'IANT Quranic Academy', 'Quran Recitation (Male)', '4th', true, 'T0FA9-ACBZO'),
  (2026, 'Ikhlas Learning Foundation', 'Ikhlas Learning Foundation', 'Quran Recitation (Male)', '5th', true, 'BIAVO-N4P6W'),
  (2026, 'The Muraqaba School', 'The Muraqaba School', 'Quran Recitation (Female)', '1st', true, 'QW9SP-ER9BC'),
  (2026, 'Excellence Academy', 'Excellence Academy', 'Quran Recitation (Female)', '2nd', true, 'RFQGL-2LECB'),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Quran Recitation (Female)', '3rd', true, 'BN4Y5-HVPSL'),
  (2026, 'Tulsa Peace Academy', 'Tulsa Peace Academy', 'Quran Recitation (Female)', '4th', true, '7TLAS-8IAOZ'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Quran Recitation (Female)', '5th', true, 'W72ZG-DZYWA'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', '2D Art', '1st', true, 'W72ZG-AAKEN'),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', '2D Art', '2nd', true, 'Z4SL7-5MJRN'),
  (2026, 'Radiant Stem Academy', 'Radiant Stem Academy', '2D Art', '3rd', true, '0THW5-0ZWXE'),
  (2026, 'Round Rock MSA', 'Round Rock MSA', '2D Art', '4th', true, 'BVKYV-34BDT'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', '2D Art', '5th', true, 'W72ZG-VXH14'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', '3D Art', '1st', true, 'W72ZG-EE6LG'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', '3D Art', '2nd', true, 'W72ZG-XN6QK'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', '3D Art', '3rd', true, 'W72ZG-VS07A'),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', '3D Art', '4th', true, 'Z4SL7-DLP84'),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', '3D Art', '5th', true, 'Z4SL7-PX498'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Fashion Design', '1st', true, 'W72ZG-7JVHN'),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Fashion Design', '2nd', true, '0CRLU-X9955'),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Fashion Design', '3rd', true, '0CRLU-8R7S0'),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Fashion Design', '4th', true, 'BN4Y5-W7Y5K'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Fashion Design', '5th', true, 'W72ZG-EDAXF'),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Digital Art', '1st', true, 'Z4SL7-5ZY8W'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Digital Art', '2nd', true, 'W72ZG-7CQB4'),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Digital Art', '3rd', true, '0CRLU-8101A'),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Digital Art', '4th', true, '0CRLU-UCXWG'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Digital Art', '5th', true, 'W72ZG-CTZFX'),
  (2026, 'Ikhlas Learning Foundation', 'Ikhlas Learning Foundation', 'Photography', '1st', true, 'BIAVO-10TPO'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Photography', '2nd', true, 'W72ZG-P6H9Z'),
  (2026, 'Texas Connections Academy', 'Texas Connections Academy', 'Photography', '3rd', true, '0PG3D-U67XJ'),
  (2026, 'Excellence Academy', 'Excellence Academy', 'Photography', '4th', true, 'RFQGL-T3F24'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Photography', '5th', true, 'W72ZG-9R6S3'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Extemporaneous Essay', '1st', true, 'W72ZG-QU01W'),
  (2026, 'Wylie High School', 'Wylie High School', 'Extemporaneous Essay', '2nd', true, 'SETQW-UZJ3C'),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Extemporaneous Essay', '3rd', true, 'Z4SL7-GJ7X6'),
  (2026, 'Texas Connections Academy', 'Texas Connections Academy', 'Extemporaneous Essay', '4th', true, '0PG3D-9YC2V'),
  (2026, 'IANT Quranic Academy', 'IANT Quranic Academy', 'Extemporaneous Essay', '5th', true, 'T0FA9-5Z3CR'),
  (2026, 'Uplift North Hills Preparatory', 'Uplift North Hills Preparatory', 'Extemporaneous Speaking', '1st', true, '5OY1R-M8ZM8'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Extemporaneous Speaking', '2nd', true, 'W72ZG-7CQB4'),
  (2026, 'Ikhlas Learning Foundation', 'Ikhlas Learning Foundation', 'Extemporaneous Speaking', '3rd', true, 'BIAVO-IK040'),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Extemporaneous Speaking', '4th', true, '0CRLU-2865N'),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Extemporaneous Speaking', '5th', true, 'BN4Y5-370BA'),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Original Oratory', '1st', true, 'Z4SL7-MDVVL'),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Original Oratory', '2nd', true, 'Z4SL7-WYX6S'),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Original Oratory', '3rd', true, '0CRLU-QOWDJ'),
  (2026, 'Radiant Stem Academy', 'Radiant Stem Academy', 'Original Oratory', '4th', true, '0THW5-MQXFP'),
  (2026, 'Tulsa Peace Academy', 'Tulsa Peace Academy', 'Original Oratory', '5th', true, '7TLAS-AI6B3'),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Poetry', '1st', true, '0CRLU-HUIND'),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Poetry', '2nd', true, '0CRLU-TO2O0'),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Poetry', '3rd', true, 'BN4Y5-PLRZ4'),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Poetry', '4th', true, 'BN4Y5-KI53Z'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Poetry', '5th', true, 'W72ZG-80VQV'),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Prepared Essay', '1st', true, '0CRLU-CV7QX'),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Prepared Essay', '2nd', true, '0CRLU-QWQI2'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Prepared Essay', '3rd', true, 'W72ZG-VXH14'),
  (2026, 'Texas Connections Academy', 'Texas Connections Academy', 'Prepared Essay', '4th', true, '0PG3D-U67XJ'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Prepared Essay', '5th', true, 'W72ZG-VKLYM'),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Short Fiction', '1st', true, '0CRLU-6769A'),
  (2026, 'Tulsa Peace Academy', 'Tulsa Peace Academy', 'Short Fiction', '2nd', true, '7TLAS-2TCBU'),
  (2026, 'Coppell High School', 'Coppell High School', 'Short Fiction', '3rd', true, 'FMZ9O-YVK9H'),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Short Fiction', '4th', true, 'BN4Y5-WA9NT'),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Short Fiction', '5th', true, 'BN4Y5-6N7UM'),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Spoken Word', '1st', true, '0CRLU-ZTDMP'),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Spoken Word', '2nd', true, 'BN4Y5-FZOBG'),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Spoken Word', '3rd', true, '0CRLU-8101A'),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Spoken Word', '4th', true, 'Z4SL7-P3KH9'),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Spoken Word', '5th', true, 'BN4Y5-Y09YI'),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Debate', '1st', true, 'Z4SL7-GJ7X6,Z4SL7-WYX6S'),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Debate', '2nd', true, '0CRLU-DBWUG,0CRLU-EV12C'),
  (2026, 'Plano East Senior High School', 'Plano East Senior High School', 'Debate', '3rd', true, '007N4-1XS9J'),
  (2026, 'Uplift North Hills Preparatory', 'Uplift North Hills Preparatory', 'Debate', '4th', true, '5OY1R-8BM2F,5OY1R-M8ZM8'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Math Olympics', '1st', true, 'W72ZG-DHB1I'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Math Olympics', '2nd', true, 'W72ZG-TRDZX'),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Math Olympics', '3rd', true, '0CRLU-G0FOY'),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Math Olympics', '4th', true, 'Z4SL7-J9655'),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Math Olympics', '5th', true, 'Z4SL7-YSQLJ'),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'MIST Quiz Bowl', '1st', true, 'Z4SL7-0K00Q,Z4SL7-4IOAM,Z4SL7-MDVVL,Z4SL7-U6ROV,Z4SL7-XPZ43,Z4SL7-ZRIB7'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'MIST Quiz Bowl', '2nd', true, 'W72ZG-4XLHN,W72ZG-7JVHN,W72ZG-AN2KE,W72ZG-EE6LG,W72ZG-VFLS6,W72ZG-XN6QK'),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'MIST Quiz Bowl', '3rd', true, '0CRLU-6769A,0CRLU-MSKST,0CRLU-QWQI2,0CRLU-RTMHQ,0CRLU-TO2O0,0CRLU-ZZ3C0'),
  (2026, 'Radiant Stem Academy', 'Radiant Stem Academy', 'MIST Quiz Bowl', '4th', true, '0THW5-3GYCO,0THW5-6KNFY,0THW5-DJ91W,0THW5-N0A1O,0THW5-PQAHM'),
  (2026, 'Coppell High School', 'Coppell High School', 'MIST Quiz Bowl', '5th', true, 'FMZ9O-3YIMP,FMZ9O-8TK94,FMZ9O-HAY0L,FMZ9O-O0YVE,FMZ9O-R0RMH,FMZ9O-YVK9H'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Improv (Male)', '1st', true, 'W72ZG-7CQB4,W72ZG-B07GM,W72ZG-C4A4E,W72ZG-JRYQ0,W72ZG-N3Y8F,W72ZG-QYR3V'),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Improv (Male)', '2nd', true, 'Z4SL7-38AWW,Z4SL7-6RTW2,Z4SL7-AEQW4,Z4SL7-PJ67T,Z4SL7-RHSH6,Z4SL7-ZOP54'),
  (2026, 'IANT Quranic Academy', 'IANT Quranic Academy', 'Improv (Male)', '3rd', true, 'T0FA9-6S113,T0FA9-918AD,T0FA9-ACBZO,T0FA9-C4VHK,T0FA9-VA2SI'),
  (2026, 'Ikhlas Learning Foundation', 'Ikhlas Learning Foundation', 'Improv (Male)', '4th', true, 'BIAVO-AAI8J,BIAVO-D23B8,BIAVO-FHMCQ,BIAVO-LYYAM,BIAVO-PECRT,BIAVO-S0A56'),
  (2026, 'Radiant Stem Academy', 'Radiant Stem Academy', 'Improv (Male)', '5th', true, '0THW5-1Z2PM,0THW5-7TDJ3,0THW5-BJ3WQ,0THW5-NWE1O,0THW5-ZKFSG'),
  (2026, 'Tulsa Peace Academy', 'Tulsa Peace Academy', 'Improv (Female)', '1st', true, '7TLAS-44EY1,7TLAS-J0SON,7TLAS-N8EBD,7TLAS-VVSDH,7TLAS-X74MM,7TLAS-YTI97'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Improv (Female)', '2nd', true, 'W72ZG-02C9P,W72ZG-A5ZY1,W72ZG-E92IF,W72ZG-QU01W,W72ZG-SOF8V,W72ZG-SWXNM'),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Improv (Female)', '3rd', true, 'Z4SL7-F1Q26,Z4SL7-KLJLB,Z4SL7-P3KH9,Z4SL7-QPE9G'),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Improv (Female)', '4th', true, 'BN4Y5-4GZ8A,BN4Y5-8VEOU,BN4Y5-FZOBG,BN4Y5-L52IU'),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Improv (Female)', '5th', true, '0CRLU-C06F5,0CRLU-N3KQU,0CRLU-Q2LPT,0CRLU-VOC1W,0CRLU-ZTDMP'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Business Venture', '1st', true, 'W72ZG-48BQY,W72ZG-AWU3N,W72ZG-BMO4F,W72ZG-MH04O,W72ZG-TXSL5,W72ZG-YCO3P'),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Business Venture', '2nd', true, 'BN4Y5-0K8R0,BN4Y5-1N70T,BN4Y5-HVPSL'),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Business Venture', '3rd', true, '0CRLU-95W81,0CRLU-A9MO3,0CRLU-DBWUG,0CRLU-FU5SE,0CRLU-H6UDL,0CRLU-V3AIS'),
  (2026, 'Texas Connections Academy', 'Texas Connections Academy', 'Business Venture', '4th', true, '0PG3D-9YC2V,0PG3D-MEX0G,0PG3D-N1N94,0PG3D-PFK8G'),
  (2026, 'Uplift North Hills Preparatory', 'Uplift North Hills Preparatory', 'Business Venture', '5th', true, '5OY1R-8AF4Z,5OY1R-I9VG3,5OY1R-OFERO,5OY1R-PB6I8,5OY1R-RDRS9,5OY1R-UOMTS'),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Humanitarian Service', '1st', true, 'BN4Y5-5ZDS4,BN4Y5-GN48R,BN4Y5-NNW8K,BN4Y5-TX6XY,BN4Y5-YQCWT,BN4Y5-YZMDX'),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Humanitarian Service', '2nd', true, '0CRLU-2JRZ2,0CRLU-QWQI2,0CRLU-X9955'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Humanitarian Service', '3rd', true, 'W72ZG-2Y1O4,W72ZG-4HDKB,W72ZG-5UYPU,W72ZG-AQMLD,W72ZG-BP935,W72ZG-EVDLG'),
  (2026, 'Tulsa Peace Academy', 'Tulsa Peace Academy', 'Humanitarian Service', '4th', true, '7TLAS-0BFVT,7TLAS-TCOP1,7TLAS-U0TT0,7TLAS-UQ432,7TLAS-Y867X'),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Humanitarian Service', '5th', true, 'Z4SL7-0K00Q,Z4SL7-DLP84,Z4SL7-HGEIN,Z4SL7-TU5MR,Z4SL7-UO78X,Z4SL7-WCGEI'),
  (2026, 'Tulsa Peace Academy', 'Tulsa Peace Academy', 'Nasheed & Rap (Male)', '1st', true, '7TLAS-C49H5,7TLAS-CHLMU,7TLAS-CUJDP,7TLAS-K7931,7TLAS-S5YJI,7TLAS-TKUHD'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Nasheed & Rap (Male)', '2nd', true, 'W72ZG-15HT7,W72ZG-AK7BQ,W72ZG-B07GM,W72ZG-H8TPQ,W72ZG-NRQ0I,W72ZG-Z6LG0'),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Nasheed & Rap (Male)', '3rd', true, '0CRLU-04QG2,0CRLU-AJ6RN,0CRLU-OO8HL,0CRLU-RTMHQ,0CRLU-SI8UB,0CRLU-ZZ3C0'),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Nasheed & Rap (Male)', '4th', true, 'Z4SL7-6RTW2,Z4SL7-CS2PY,Z4SL7-KFLFG,Z4SL7-QM5RG,Z4SL7-WBB23'),
  (2026, 'IANT Quranic Academy', 'IANT Quranic Academy', 'Nasheed & Rap (Male)', '5th', true, 'T0FA9-918AD,T0FA9-ACBZO,T0FA9-CACMV,T0FA9-DK7F7,T0FA9-WMYUP'),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Nasheed & Rap (Female)', '1st', true, 'BN4Y5-3FET4,BN4Y5-AO3Y4,BN4Y5-FLDV5,BN4Y5-SMY6G'),
  (2026, 'Tulsa Peace Academy', 'Tulsa Peace Academy', 'Nasheed & Rap (Female)', '2nd', true, '7TLAS-5E2FQ,7TLAS-8IAOZ,7TLAS-LJCAQ,7TLAS-VVSDH,7TLAS-X74MM,7TLAS-Y9G8I'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Nasheed & Rap (Female)', '3rd', true, 'W72ZG-3VHQF,W72ZG-9LZEA,W72ZG-BU9KW,W72ZG-H39KI,W72ZG-KOU31,W72ZG-LKUHI'),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Nasheed & Rap (Female)', '4th', true, 'Z4SL7-JPSAG,Z4SL7-VSIXT,Z4SL7-YW3QY,Z4SL7-Z5BM9'),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Nasheed & Rap (Female)', '5th', true, '0CRLU-EV12C,0CRLU-GSPQ0,0CRLU-JKURB,0CRLU-MJ4JI,0CRLU-WALEQ'),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Science Fair', '1st', true, 'Z4SL7-ZOP54'),
  (2026, 'Uplift North Hills Preparatory', 'Uplift North Hills Preparatory', 'Science Fair', '2nd', true, '5OY1R-6J0LC,5OY1R-BRC69,5OY1R-D6LRV,5OY1R-XP6NB'),
  (2026, 'Radiant Stem Academy', 'Radiant Stem Academy', 'Science Fair', '3rd', true, '0THW5-96IYC,0THW5-MQXFP'),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Science Fair', '4th', true, '0CRLU-1PQ40,0CRLU-2UMNB,0CRLU-KEC12,0CRLU-ZICA0'),
  (2026, 'Texas Connections Academy', 'Texas Connections Academy', 'Science Fair', '5th', true, '0PG3D-MVC2R,0PG3D-U67XJ'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Short Film', '1st', true, 'W72ZG-7JVHN,W72ZG-AI8IV,W72ZG-EE6LG,W72ZG-G1OCW,W72ZG-KNH1N,W72ZG-MHUJT'),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Short Film', '2nd', true, '0CRLU-4S9LS,0CRLU-5SY7Q,0CRLU-8566Y,0CRLU-F99DR,0CRLU-GB9D7,0CRLU-QT6EQ'),
  (2026, 'Radiant Stem Academy', 'Radiant Stem Academy', 'Short Film', '3rd', true, '0THW5-1H6KV,0THW5-3SVRC,0THW5-5X629,0THW5-97N57,0THW5-BJ3WQ,0THW5-CL3AV'),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Short Film', '4th', true, 'BN4Y5-37MQ4,BN4Y5-4GZ8A,BN4Y5-7VTPU,BN4Y5-H6IQF,BN4Y5-S7WOF,BN4Y5-ZAPGH'),
  (2026, 'Ranchview High School', 'Ranchview High School', 'Short Film', '5th', true, 'PK172-8SZDB,PK172-CU326,PK172-G08SC,PK172-NCWLV,PK172-QHTK6,PK172-TCTW4'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Social Media', '1st', true, 'W72ZG-7CQB4,W72ZG-C4A4E,W72ZG-GWF54,W72ZG-SWXNM,W72ZG-WR1SL,W72ZG-Z3SXD'),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Social Media', '2nd', true, 'BN4Y5-ECFN1,BN4Y5-G3JDS,BN4Y5-WOFDR,BN4Y5-XY1VF,BN4Y5-Y09YI'),
  (2026, 'Ikhlas Learning Foundation', 'Ikhlas Learning Foundation', 'Social Media', '3rd', true, 'BIAVO-1BZ2B,BIAVO-LBFU8,BIAVO-PLFQG,BIAVO-Q3B59'),
  (2026, 'IANT Quranic Academy', 'IANT Quranic Academy', 'Social Media', '4th', true, 'T0FA9-HETMZ,T0FA9-VA2SI'),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Social Media', '5th', true, '0CRLU-AKGQW,0CRLU-TO2O0,0CRLU-UCXWG,0CRLU-VOC1W,0CRLU-ZTDMP'),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Basketball (Male)', '1st', true, 'Z4SL7-6RTW2,Z4SL7-D82NY,Z4SL7-HGEIN,Z4SL7-IUTF0,Z4SL7-PNT3U,Z4SL7-QTHCR,Z4SL7-RO7ER,Z4SL7-TWN06,Z4SL7-WBB23,Z4SL7-XPZ43'),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Basketball (Male)', '2nd', true, 'W72ZG-15HT7,W72ZG-83CWY,W72ZG-B07GM,W72ZG-KNH1N,W72ZG-MH04O,W72ZG-TXSL5,W72ZG-UT4RC,W72ZG-YCO3P'),
  (2026, 'Radiant Stem Academy', 'Radiant Stem Academy', 'Basketball (Male)', '3rd', true, '0THW5-1H6KV,0THW5-1Z2PM,0THW5-5X629,0THW5-7TDJ3,0THW5-97N57,0THW5-BJ3WQ,0THW5-CL3AV,0THW5-GXP0H,0THW5-NWE1O,0THW5-W1K87'),
  (2026, 'Coalition (Ikhlas LF + Excellence Academy)', 'Coalition (Ikhlas LF + Excellence Academy)', 'Basketball (Female)', '1st', true, 'BIAVO-1BZ2B,BIAVO-1OV5Y,BIAVO-863E9,BIAVO-9AXPO,BIAVO-IK040,BIAVO-X2F0W,RFQGL-2LECB,RFQGL-B9VPQ,RFQGL-OWSBD,RFQGL-XIMFS'),
  (2026, 'IANT Quranic Academy', 'IANT Quranic Academy', 'Basketball (Female)', '2nd', true, 'T0FA9-076AB,T0FA9-0TG3K,T0FA9-77Y52,T0FA9-7B68U,T0FA9-EY973,T0FA9-HETMZ,T0FA9-OCL0Q,T0FA9-OZ5WP,T0FA9-RL5CG'),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Basketball (Female)', '3rd', true, 'Z4SL7-1RIBX,Z4SL7-3D1IT,Z4SL7-9OLRP,Z4SL7-F1Q26,Z4SL7-JPSAG,Z4SL7-O1AZZ,Z4SL7-QPE9G,Z4SL7-RDA78');
