-- MIST Dallas 2026 National Qualifiers
-- Run in Supabase SQL Editor > New query
-- category = specific event name (broad category derived in frontend)

INSERT INTO qualifiers (year, name, school, category, placement, qualified_for_nationals) VALUES
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Knowledge Test 1', '1st', true),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Knowledge Test 1', '2nd', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Knowledge Test 1', '3rd', true),
  (2026, 'Tulsa Peace Academy', 'Tulsa Peace Academy', 'Knowledge Test 1', '4th', true),
  (2026, 'Uplift North Hills Preparatory', 'Uplift North Hills Preparatory', 'Knowledge Test 1', '5th', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Knowledge Test 2', '1st', true),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Knowledge Test 2', '2nd', true),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Knowledge Test 2', '3rd', true),
  (2026, 'Wylie High School', 'Wylie High School', 'Knowledge Test 2', '4th', true),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Knowledge Test 2', '5th', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Knowledge Test 3', '1st', true),
  (2026, 'Plano East Senior High School', 'Plano East Senior High School', 'Knowledge Test 3', '2nd', true),
  (2026, 'Tulsa Peace Academy', 'Tulsa Peace Academy', 'Knowledge Test 3', '3rd', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Knowledge Test 3', '4th', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Knowledge Test 3', '5th', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Knowledge Test 4', '1st', true),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Knowledge Test 4', '2nd', true),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Knowledge Test 4', '3rd', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Knowledge Test 4', '4th', true),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Knowledge Test 4', '5th', true),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Quran Memorization — Lvl 1 (Male)', '1st', true),
  (2026, 'Good Tree Academy', 'Good Tree Academy', 'Quran Memorization — Lvl 1 (Male)', '2nd', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Quran Memorization — Lvl 1 (Male)', '3rd', true),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Quran Memorization — Lvl 1 (Male)', '4th', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Quran Memorization — Lvl 1 (Male)', '5th', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Quran Memorization — Lvl 1 (Female)', '1st', true),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Quran Memorization — Lvl 1 (Female)', '2nd', true),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Quran Memorization — Lvl 1 (Female)', '3rd', true),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Quran Memorization — Lvl 1 (Female)', '4th', true),
  (2026, 'The Muraqaba School', 'The Muraqaba School', 'Quran Memorization — Lvl 1 (Female)', '5th', true),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Quran Memorization — Lvl 2 (Male)', '1st', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Quran Memorization — Lvl 2 (Male)', '2nd', true),
  (2026, 'Ikhlas Learning Foundation', 'Ikhlas Learning Foundation', 'Quran Memorization — Lvl 2 (Male)', '3rd', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Quran Memorization — Lvl 2 (Male)', '4th', true),
  (2026, 'Plano East Senior High School', 'Plano East Senior High School', 'Quran Memorization — Lvl 2 (Male)', '5th', true),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Quran Memorization — Lvl 2 (Female)', '1st', true),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Quran Memorization — Lvl 2 (Female)', '2nd', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Quran Memorization — Lvl 2 (Female)', '3rd', true),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Quran Memorization — Lvl 2 (Female)', '4th', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Quran Memorization — Lvl 2 (Female)', '5th', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Quran Memorization — Lvl 3 (Male)', '1st', true),
  (2026, 'Epic Darul Quran Hifz School', 'Epic Darul Quran Hifz School', 'Quran Memorization — Lvl 3 (Male)', '2nd', true),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Quran Memorization — Lvl 3 (Male)', '3rd', true),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Quran Memorization — Lvl 3 (Male)', '4th', true),
  (2026, 'Plano East Senior High School', 'Plano East Senior High School', 'Quran Memorization — Lvl 3 (Male)', '5th', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Quran Memorization — Lvl 3 (Female)', '1st', true),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Quran Memorization — Lvl 3 (Female)', '2nd', true),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Quran Memorization — Lvl 3 (Female)', '3rd', true),
  (2026, 'Good Tree Academy', 'Good Tree Academy', 'Quran Memorization — Lvl 3 (Female)', '4th', true),
  (2026, 'Ikhlas Learning Foundation', 'Ikhlas Learning Foundation', 'Quran Memorization — Lvl 3 (Female)', '5th', true),
  (2026, 'Epic Darul Quran Hifz School', 'Epic Darul Quran Hifz School', 'Quran Recitation (Male)', '1st', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Quran Recitation (Male)', '2nd', true),
  (2026, 'IANT Quranic Academy', 'IANT Quranic Academy', 'Quran Recitation (Male)', '3rd', true),
  (2026, 'IANT Quranic Academy', 'IANT Quranic Academy', 'Quran Recitation (Male)', '4th', true),
  (2026, 'Ikhlas Learning Foundation', 'Ikhlas Learning Foundation', 'Quran Recitation (Male)', '5th', true),
  (2026, 'The Muraqaba School', 'The Muraqaba School', 'Quran Recitation (Female)', '1st', true),
  (2026, 'Excellence Academy', 'Excellence Academy', 'Quran Recitation (Female)', '2nd', true),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Quran Recitation (Female)', '3rd', true),
  (2026, 'Tulsa Peace Academy', 'Tulsa Peace Academy', 'Quran Recitation (Female)', '4th', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Quran Recitation (Female)', '5th', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', '2D Art', '1st', true),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', '2D Art', '2nd', true),
  (2026, 'Radiant Stem Academy', 'Radiant Stem Academy', '2D Art', '3rd', true),
  (2026, 'Round Rock MSA', 'Round Rock MSA', '2D Art', '4th', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', '2D Art', '5th', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', '3D Art', '1st', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', '3D Art', '2nd', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', '3D Art', '3rd', true),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', '3D Art', '4th', true),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', '3D Art', '5th', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Fashion Design', '1st', true),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Fashion Design', '2nd', true),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Fashion Design', '3rd', true),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Fashion Design', '4th', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Fashion Design', '5th', true),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Digital Art', '1st', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Digital Art', '2nd', true),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Digital Art', '3rd', true),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Digital Art', '4th', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Digital Art', '5th', true),
  (2026, 'Ikhlas Learning Foundation', 'Ikhlas Learning Foundation', 'Photography', '1st', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Photography', '2nd', true),
  (2026, 'Texas Connections Academy', 'Texas Connections Academy', 'Photography', '3rd', true),
  (2026, 'Excellence Academy', 'Excellence Academy', 'Photography', '4th', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Photography', '5th', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Extemporaneous Essay', '1st', true),
  (2026, 'Wylie High School', 'Wylie High School', 'Extemporaneous Essay', '2nd', true),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Extemporaneous Essay', '3rd', true),
  (2026, 'Texas Connections Academy', 'Texas Connections Academy', 'Extemporaneous Essay', '4th', true),
  (2026, 'IANT Quranic Academy', 'IANT Quranic Academy', 'Extemporaneous Essay', '5th', true),
  (2026, 'Uplift North Hills Preparatory', 'Uplift North Hills Preparatory', 'Extemporaneous Speaking', '1st', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Extemporaneous Speaking', '2nd', true),
  (2026, 'Ikhlas Learning Foundation', 'Ikhlas Learning Foundation', 'Extemporaneous Speaking', '3rd', true),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Extemporaneous Speaking', '4th', true),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Extemporaneous Speaking', '5th', true),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Original Oratory', '1st', true),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Original Oratory', '2nd', true),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Original Oratory', '3rd', true),
  (2026, 'Radiant Stem Academy', 'Radiant Stem Academy', 'Original Oratory', '4th', true),
  (2026, 'Tulsa Peace Academy', 'Tulsa Peace Academy', 'Original Oratory', '5th', true),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Poetry', '1st', true),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Poetry', '2nd', true),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Poetry', '3rd', true),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Poetry', '4th', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Poetry', '5th', true),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Prepared Essay', '1st', true),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Prepared Essay', '2nd', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Prepared Essay', '3rd', true),
  (2026, 'Texas Connections Academy', 'Texas Connections Academy', 'Prepared Essay', '4th', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Prepared Essay', '5th', true),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Short Fiction', '1st', true),
  (2026, 'Tulsa Peace Academy', 'Tulsa Peace Academy', 'Short Fiction', '2nd', true),
  (2026, 'Coppell High School', 'Coppell High School', 'Short Fiction', '3rd', true),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Short Fiction', '4th', true),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Short Fiction', '5th', true),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Spoken Word', '1st', true),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Spoken Word', '2nd', true),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Spoken Word', '3rd', true),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Spoken Word', '4th', true),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Spoken Word', '5th', true),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Debate', '1st', true),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Debate', '2nd', true),
  (2026, 'Plano East Senior High School', 'Plano East Senior High School', 'Debate', '3rd', true),
  (2026, 'Uplift North Hills Preparatory', 'Uplift North Hills Preparatory', 'Debate', '4th', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Math Olympics', '1st', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Math Olympics', '2nd', true),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Math Olympics', '3rd', true),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Math Olympics', '4th', true),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Math Olympics', '5th', true),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'MIST Quiz Bowl', '1st', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'MIST Quiz Bowl', '2nd', true),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'MIST Quiz Bowl', '3rd', true),
  (2026, 'Radiant Stem Academy', 'Radiant Stem Academy', 'MIST Quiz Bowl', '4th', true),
  (2026, 'Coppell High School', 'Coppell High School', 'MIST Quiz Bowl', '5th', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Improv (Male)', '1st', true),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Improv (Male)', '2nd', true),
  (2026, 'IANT Quranic Academy', 'IANT Quranic Academy', 'Improv (Male)', '3rd', true),
  (2026, 'Ikhlas Learning Foundation', 'Ikhlas Learning Foundation', 'Improv (Male)', '4th', true),
  (2026, 'Radiant Stem Academy', 'Radiant Stem Academy', 'Improv (Male)', '5th', true),
  (2026, 'Tulsa Peace Academy', 'Tulsa Peace Academy', 'Improv (Female)', '1st', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Improv (Female)', '2nd', true),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Improv (Female)', '3rd', true),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Improv (Female)', '4th', true),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Improv (Female)', '5th', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Business Venture', '1st', true),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Business Venture', '2nd', true),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Business Venture', '3rd', true),
  (2026, 'Texas Connections Academy', 'Texas Connections Academy', 'Business Venture', '4th', true),
  (2026, 'Uplift North Hills Preparatory', 'Uplift North Hills Preparatory', 'Business Venture', '5th', true),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Humanitarian Service', '1st', true),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Humanitarian Service', '2nd', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Humanitarian Service', '3rd', true),
  (2026, 'Tulsa Peace Academy', 'Tulsa Peace Academy', 'Humanitarian Service', '4th', true),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Humanitarian Service', '5th', true),
  (2026, 'Tulsa Peace Academy', 'Tulsa Peace Academy', 'Nasheed & Rap (Male)', '1st', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Nasheed & Rap (Male)', '2nd', true),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Nasheed & Rap (Male)', '3rd', true),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Nasheed & Rap (Male)', '4th', true),
  (2026, 'IANT Quranic Academy', 'IANT Quranic Academy', 'Nasheed & Rap (Male)', '5th', true),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Nasheed & Rap (Female)', '1st', true),
  (2026, 'Tulsa Peace Academy', 'Tulsa Peace Academy', 'Nasheed & Rap (Female)', '2nd', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Nasheed & Rap (Female)', '3rd', true),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Nasheed & Rap (Female)', '4th', true),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Nasheed & Rap (Female)', '5th', true),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Science Fair', '1st', true),
  (2026, 'Uplift North Hills Preparatory', 'Uplift North Hills Preparatory', 'Science Fair', '2nd', true),
  (2026, 'Radiant Stem Academy', 'Radiant Stem Academy', 'Science Fair', '3rd', true),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Science Fair', '4th', true),
  (2026, 'Texas Connections Academy', 'Texas Connections Academy', 'Science Fair', '5th', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Short Film', '1st', true),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Short Film', '2nd', true),
  (2026, 'Radiant Stem Academy', 'Radiant Stem Academy', 'Short Film', '3rd', true),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Short Film', '4th', true),
  (2026, 'Ranchview High School', 'Ranchview High School', 'Short Film', '5th', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Social Media', '1st', true),
  (2026, 'Qalam Collegiate Academy', 'Qalam Collegiate Academy', 'Social Media', '2nd', true),
  (2026, 'Ikhlas Learning Foundation', 'Ikhlas Learning Foundation', 'Social Media', '3rd', true),
  (2026, 'IANT Quranic Academy', 'IANT Quranic Academy', 'Social Media', '4th', true),
  (2026, 'Austin Peace Academy', 'Austin Peace Academy', 'Social Media', '5th', true),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Basketball (Male)', '1st', true),
  (2026, 'Islamic School of Irving', 'Islamic School of Irving', 'Basketball (Male)', '2nd', true),
  (2026, 'Radiant Stem Academy', 'Radiant Stem Academy', 'Basketball (Male)', '3rd', true),
  (2026, 'Coalition (Ikhlas LF + Excellence Academy)', 'Coalition (Ikhlas LF + Excellence Academy)', 'Basketball (Female)', '1st', true),
  (2026, 'IANT Quranic Academy', 'IANT Quranic Academy', 'Basketball (Female)', '2nd', true),
  (2026, 'Brighter Horizons Academy', 'Brighter Horizons Academy', 'Basketball (Female)', '3rd', true);
